[pios_compatibility]
help="Makes maintaining program compatibility with different versions of PiOS easier"
revision=1
uses=[]
requires=["packaging"]

[pios_sdk_info]
help="Provides SDK Information by which the program is built"
revision=1
uses=[]
requires=[]

[pios_terminal]
help="Provides a standard interface for accessing and using the pios terminal"
revision=1
uses=[]
requires=[]

[github_guest]
help="Provides a anonymous interface to github for file downloading or repo downloading"
revision=1
uses=[]
requires=["requests"]
